/**
 * Generates a Markdown documentation string from normalized integration metadata.
 * @param {IntegrationMetadata} metadata - Output from iarParser or jsonParser
 * @returns {string} - Full Markdown document
 */
export function generateMarkdown(metadata) {
    const sections = [
      buildHeader(metadata),
      buildOverview(metadata),
      buildTriggers(metadata.triggers),
      buildInvokes(metadata.invokes),
      buildFaultHandlers(metadata.faultHandlers),
      buildVariables(metadata.variables),
      buildFooter(),
    ]
  
    return sections.filter(Boolean).join("\n\n---\n\n")
  }
  
  // ─────────────────────────────────────────────
  // Section builders
  // ─────────────────────────────────────────────
  
  function buildHeader({ integrationName, version }) {
    return [
      `# ${integrationName}`,
      `> **Version:** ${version}`,
    ].join("\n")
  }
  
  function buildOverview({ description, pattern, source, fileName }) {
    const lines = ["## Overview"]
  
    if (description) lines.push(description)
  
    lines.push(buildTable(
      ["Field", "Value"],
      [
        ["Pattern", pattern],
        ["Source", source === "iar" ? `IAR Archive (${fileName})` : "JSON Metadata"],
        ["Generated", new Date().toUTCString()],
      ]
    ))
  
    return lines.join("\n\n")
  }
  
  function buildTriggers(triggers) {
    if (!triggers.length) return null
  
    return [
      "## Triggers",
      `_${triggers.length} trigger(s) found_`,
      buildTable(
        ["Name", "Type", "Connection"],
        triggers.map((t) => [t.name, t.type, t.connection || "—"])
      ),
    ].join("\n\n")
  }
  
  function buildInvokes(invokes) {
    if (!invokes.length) return null
  
    return [
      "## Invoke Connections",
      `_${invokes.length} invoke(s) found_`,
      buildTable(
        ["Name", "Type", "Connection", "Operation"],
        invokes.map((i) => [i.name, i.type, i.connection || "—", i.operation || "—"])
      ),
    ].join("\n\n")
  }
  
  function buildFaultHandlers(faultHandlers) {
    if (!faultHandlers.length) return null
  
    return [
      "## Fault Handlers",
      `_${faultHandlers.length} fault handler(s) found_`,
      buildTable(
        ["Name", "Fault Name", "Action"],
        faultHandlers.map((f) => [f.name, f.faultName || "—", f.action])
      ),
    ].join("\n\n")
  }
  
  function buildVariables(variables) {
    if (!variables.length) return null
  
    return [
      "## Variables",
      `_${variables.length} variable(s) found_`,
      buildTable(
        ["Name", "Type", "Scope"],
        variables.map((v) => [v.name, v.type, v.scope])
      ),
    ].join("\n\n")
  }
  
  function buildFooter() {
    return `_Documentation generated by OIC Doc Generator_`
  }
  
  // ─────────────────────────────────────────────
  // Utility
  // ─────────────────────────────────────────────
  
  /**
   * Builds a Markdown table string.
   * @param {string[]} headers
   * @param {string[][]} rows
   */
  function buildTable(headers, rows) {
    const separator = headers.map(() => "---")
  
    const toRow = (cols) => `| ${cols.join(" | ")} |`
  
    return [
      toRow(headers),
      toRow(separator),
      ...rows.map(toRow),
    ].join("\n")
  }